# Generated by Django 5.1.1 on 2024-10-07 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_gameplayerstats_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerShots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_make', models.BooleanField()),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('game_player_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gameplayerstats')),
            ],
        ),
    ]
